name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: depth
      - name: Build depth's module
        working-directory: depth
        run: cargo build --target wasm32-wasip2 --release

  build-shots:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: shots
      - name: Build shots' module
        working-directory: shots
        run: cargo build --target wasm32-wasip2 --release

  build-mask-tools:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: mask_tools
      - name: Install ffrwd and spans_mask's wit
        working-directory: mask_tools
        run: |
          pip install ffrwd
          ffrwd install
      - name: Build mask_tools' modules
        working-directory: mask_tools
        run: cargo build --target wasm32-wasip2 --release
      - name: Unit tests
        working-directory: mask_tools
        run: cargo test --release
